import dedent from 'dedent';
import { z } from 'zod';

import { parseJsonResponse } from '../../response-parsers/parseJsonResponse';
import type {
    FunctionCallMessage,
    FunctionDescription,
    Message,
    RegularAssistantMessage,
    RegularMessage,
    ToolCallsMessage,
} from '../api';

/**
 * For a model that doesn't support functions or tools, this function creates a message
 * that describes the functions calling mechanism to the LLM, so that we can attempt
 * to emulation function calling similar to OpenAI API.
 */
export function adaptFunctionsToDescriptionMessage<
    R extends 'user' | 'system',
>(opts: {
    /**
     * The role of the resulting message
     */
    role: R;
    /**
     * Functions available to be called
     */
    functions: Array<FunctionDescription>;
}): Array<{ role: R; content: string }> {
    const { functions, role } = opts;
    if (functions.length === 0) {
        return [];
    }

    const header = dedent`
        You can also call functions. Calling a function allows you to perform 
        an action and then continue the conversation with the result of the
        function execution in the context. To call a function return a message
        with the following structure:

        \`\`\`json
        [{
            "id": "uniqueIdOfTheFunctionCall",
            "name": "functionName",
            "arguments": {
                "param1": "value1"
            }
        }]
        \`\`\`

        To call multiple functions, add multiple entries to the array. You
        cannot call a function and respond to other user messages at the same
        time. You will have an opportunity to respond to user messages after
        the function execution.

        Following functions are available:
    `;

    return [
        {
            role,
            content:
                header +
                functions
                    .map(
                        (fn) =>
                            dedent`
                                - "${fn.name}"

                                ${fn.description}

                                ${JSON.stringify(
                                    fn.parameters,
                                    undefined,
                                    '  '
                                )}
                            `
                    )
                    .join('\n\n'),
        },
    ];
}

/**
 * This function converts messages that represent OpenAI function calls and
 * tool calls to regular messages of type "assistant" where the function call
 * parameters are serialized as JSON code block as per description generated by
 * @see adaptFunctionsToDescriptionMessage.
 *
 * This is intended to be used when the LLM doesn't support function calls.
 */
export function adaptFunctionsCallsAndResultsToRegularMessages(
    messages: Array<Message>
): Array<RegularMessage | RegularAssistantMessage> {
    if (messages.length === 0) {
        return [];
    }

    const parsedJsonSchema = z
        .string()
        .transform((text) => JSON.parse(text) as Record<string, unknown>)
        .or(z.string());

    return messages.map((message, i) => {
        if ('functionCall' in message) {
            return {
                role: 'assistant' as const,
                content: dedent`
                    ~~~json
                    ${JSON.stringify(
                        {
                            id: i.toString(),
                            name: message.functionCall.name,
                            arguments: parsedJsonSchema.parse(
                                message.functionCall.arguments
                            ),
                        },
                        undefined,
                        2
                    )}
                    ~~~
                `,
            };
        }

        if ('toolCalls' in message) {
            return {
                role: 'assistant' as const,
                content: dedent`
                    ~~~json
                    ${JSON.stringify(
                        message.toolCalls.map((toolCall) => ({
                            id: toolCall.id,
                            name: toolCall.function.name,
                            arguments: parsedJsonSchema.parse(
                                toolCall.function.arguments
                            ),
                        })),
                        undefined,
                        '  '
                    )}
                    ~~~
                `,
            };
        }

        if ('toolCallId' in message) {
            const call = messages
                .flatMap((m) => ('toolCalls' in m ? m.toolCalls : []))
                .find((call) => call.id === message.toolCallId);
            return {
                role: 'user' as const,
                content: dedent`
                    ~~~json
                    ${JSON.stringify(
                        {
                            toolCallId: message.toolCallId,
                            ...(call && {
                                name: call.function.name,
                                arguments: call.function.arguments,
                            }),
                            result: parsedJsonSchema.parse(message.content),
                        },
                        undefined,
                        '  '
                    )}
                    ~~~
                `,
            };
        }

        if (message.role === 'function') {
            const callIndex = messages
                .flatMap((m) => ('functionCall' in m ? m.functionCall : []))
                .reverse()
                .findIndex((call) => call.name === message.name);
            const call =
                callIndex >= 0
                    ? (messages[
                          messages.length - callIndex
                      ] as FunctionCallMessage)
                    : undefined;

            return {
                role: 'user' as const,
                content: dedent`
                    ~~~json
                    ${JSON.stringify(
                        {
                            ...(call && {
                                toolCallId: callIndex.toString(),
                                arguments: parsedJsonSchema.parse(
                                    call.functionCall.arguments
                                ),
                            }),
                            name: message.name,
                            result: parsedJsonSchema.parse(message.content),
                        },
                        undefined,
                        '  '
                    )}
                    ~~~
                `,
            };
        }

        return message satisfies RegularMessage;
    });
}

const syntheticCallFunctionSchema = z.array(
    z.object({
        id: z.string(),
        name: z.string(),
        arguments: z.unknown().optional(),
    })
);

/**
 * Converts regular messages to function calls and tool calls as per description
 * generated by @see adaptFunctionsToDescriptionMessage
 *
 * This is the opposite of @see adaptFunctionsCallsAndResultsToRegularMessages
 */
export function adaptRegularMessagesToFunctionCalls(
    message: ToolCallsMessage | FunctionCallMessage | RegularAssistantMessage
): ToolCallsMessage | FunctionCallMessage | RegularAssistantMessage {
    if ('functionCall' in message) {
        return message;
    }
    if ('toolCalls' in message) {
        return message;
    }

    if (message.content.includes('"name"')) {
        try {
            const result = parseJsonResponse({
                response: message.content,
                schema: syntheticCallFunctionSchema,
                allowMultiple: true,
            }).flatMap((result) => result);

            return {
                role: 'assistant' as const,
                toolCalls: result.map((call) => ({
                    id: call.id,
                    type: 'function' as const,
                    function: {
                        name: call.name,
                        arguments: JSON.stringify(call.arguments),
                    },
                })),
            };
        } catch (err) {
            return message;
        }
    }

    return message;
}
